package templates

var FileRW = `// Code generated by thriftgo ({{Version}}). DO NOT EDIT.
{{InsertionPoint "bof"}}
package {{.FilePackage}}

import (
	"context"
	"fmt"
	"reflect"
	"github.com/apache/thrift/lib/go/thrift"
)

var (
	_ = context.Background()
	_ = fmt.Formatter(nil)
	_ = reflect.Type(nil)
	_ = thrift.TProtocol(nil)
)

{{- range .Structs}}
{{ template "StructLikeRW" .}}
{{- end}}

{{- range .Unions}}
{{template "StructLikeRW" .}}
{{- end}}

{{- range .Exceptions}}
{{template "StructLikeRW" .}}
{{- end}}

{{- range .Services}}
{{template "ProcessorRW" .}}
{{- end}}

{{- InsertionPoint "eof"}}
`
